environment: 
  device: cuda
  root: ./db
  features: features
  lst_keyframes: 
    path: s_optimized_keyframes
    format: .webp
  vid_url: vid_url.json

translation: google

llm: 
  provider: groq
  api_key: None 
  llm_config: 
    temperature: 1.0

clip: 
  model_name: openai/clip-vit-base-patch32
  bin_name: clipB32

blip: 
  model_name: blip2_feature_extractor
  bin_name: blip2fe