services:
  web: 
    build: ./backend
    container_name: hcmc-backend
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports: 
      - 8000:8000
    volumes:
      - .:/backend
    depends_on:
      - db
    environment:
      - PYTORCH_CUDA_VISIBLE_DEVICES=0  # Assuming you have one GPU

  db:
    build: ./db
    volumes:
      - ./db:/db